FROM node:14.6.0-alpine

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-api-gateway

WORKDIR /data/freelog-api-gateway

COPY . /data/freelog-api-gateway

RUN npm install

ENV NODE_ENV deve
ENV EGG_SERVER_ENV deve
ENV PORT 8895
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 8895

CMD [ "npm", "start" ]

# 本地虚拟机构建
# docker stop freelog-api-gateway
# docker rm freelog-api-gateway
# docker rmi freelog-api-gateway
# cd /mnt/hgfs/share/freelog-api-gateway
# docker build -t freelog-api-gateway -f=Dockerfile-deve .
# docker run --name="freelog-api-gateway" -p 8895:8895 -d  freelog-api-gateway